<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Student;
use App\Models\StudentPersonalData;
use App\Models\StudentFamilyData;
use App\Models\StudentAcademicData;
use App\Models\StudentLearningResources;
use App\Models\StudentPsychosocialData;
use App\Models\StudentNeedsAssessment;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->seedStudent(
            userData: [
                'first_name' => 'Geff Kendra',
                'middle_name' => 'Calumpag',
                'last_name' => 'Gaviola',
                'birthdate' => '2003-12-14',
                'age' => 21,
                'sex' => 'female',
                'birthplace' => 'Iligan City',
                'religion' => 'SDA',
                'civil_status' => 'single',
                'number_of_children' => 0,
                'citizenship' => 'Filipino',
                'address' => 'Iligan City',
                'region_of_residence' => 'Region X',
                'phone_number' => '09952796162',
                'email' => 'geff114@gmail.com',
                'password' => Hash::make('1234567890'),
                'role' => 'student',
            ],
            studentData: [
                'student_id' => '2022-2622',
                'year_level' => '1st Year',
                'course' => 'Bachelor of Science in Computer Science',
                'college_id' => 7,
                'msu_sase_score' => 85.5,
                'academic_year' => '2024-2025',
                'profile_picture' => null,
                'student_status' => 'new',
                'initial_interview_completed' => false,
            ],
            relations: [
                'personal' => [
                    'nickname' => 'Geff',
                    'home_address' => 'Tibanga, Iligan City',
                    'stays_with' => 'parents/guardian',
                    'working_student' => 'no and have no plan to work',
                    'talents_skills' => ['programming', 'web development', 'problem solving'],
                    'leisure_activities' => ['reading', 'coding', 'gaming'],
                    'serious_medical_condition' => 'None',
                    'physical_disability' => 'None',
                    'sex_identity' => 'female/woman',
                    'romantic_attraction' => 'opposite sex',
                ],
                'family' => [
                    'father_name' => 'Juan Gaviola',
                    'father_deceased' => false,
                    'father_occupation' => 'Engineer',
                    'father_phone_number' => '09123456789',
                    'mother_name' => 'Maria Gaviola',
                    'mother_deceased' => false,
                    'mother_occupation' => 'Teacher',
                    'mother_phone_number' => '09198765432',
                    'parents_marital_status' => 'married',
                    'family_monthly_income' => '15001-20000',
                    'guardian_name' => null,
                    'guardian_occupation' => null,
                    'guardian_phone_number' => null,
                    'guardian_relationship' => null,
                    'ordinal_position' => 'eldest',
                    'number_of_siblings' => 2,
                    'home_environment_description' => 'Supportive and nurturing family environment',
                ],
                'academic' => [
                    'shs_gpa' => 92.5,
                    'is_scholar' => true,
                    'scholarship_type' => 'Academic Scholar',
                    'school_last_attended' => 'Iligan City National High School',
                    'school_address' => 'Iligan City',
                    'shs_track' => 'academic',
                    'shs_strand' => 'STEM',
                    'awards_honors' => ['Valedictorian', 'Best in Math'],
                    'student_organizations' => ['Math Club', 'Programming Club'],
                    'co_curricular_activities' => ['Robotics Competition', 'Math Olympiad'],
                    'career_option_1' => 'Software Developer',
                    'career_option_2' => 'Data Scientist',
                    'career_option_3' => 'Web Developer',
                    'course_choice_by' => 'own choice',
                    'course_choice_reason' => 'Passion for technology and programming',
                    'msu_choice_reasons' => ['quality education', 'affordable tuition fees', 'prestigious institution'],
                    'future_career_plans' => 'Become a software engineer and work in tech industry',
                ],
                'learning_resources' => [
                    'internet_access' => 'full internet access',
                    'technology_gadgets' => ['laptop/notebook', 'mobile phone smartphone'],
                    'internet_connectivity' => ['home internet'],
                    'distance_learning_readiness' => 'fully ready',
                    'learning_space_description' => 'Quiet room with desk and computer',
                ],
                'psychosocial' => [
                    'personality_characteristics' => ['organized', 'analytical', 'introverted'],
                    'coping_mechanisms' => ['listening to music', 'talking to friends'],
                    'mental_health_perception' => 'Generally good, occasional stress',
                    'had_counseling_before' => false,
                    'sought_psychologist_help' => false,
                    'problem_sharing_targets' => ['friends', 'mother'],
                    'needs_immediate_counseling' => false,
                    'future_counseling_concerns' => 'Academic pressure and career decisions',
                ],
                'needs_assessment' => [
                    'improvement_needs' => ['Time-management skills', 'Test-taking skills'],
                    'financial_assistance_needs' => ['Grants/scholarships'],
                    'personal_social_needs' => ['Stress management', 'Motivation'],
                    'stress_responses' => ['Hurt myself', 'Tried to solve my problem'],
                    'easy_discussion_target' => 'friends/relatives',
                    'counseling_perceptions' => [
                        'I know that help is available at the Guidance and Counseling Center of MSU-IIT.' => 'always',
                        'I am shy to ask assistance/seek counseling from my guidance counselor.' => 'sometimes',
                    ],
                ],
            ]
        );

        $this->seedStudent(
            userData: [
                'first_name' => 'Maria',
                'middle_name' => 'Santos',
                'last_name' => 'Reyes',
                'birthdate' => '2004-03-22',
                'age' => 20,
                'sex' => 'female',
                'birthplace' => 'Cagayan de Oro City',
                'religion' => 'Catholic',
                'civil_status' => 'single',
                'number_of_children' => 0,
                'citizenship' => 'Filipino',
                'address' => 'Cagayan de Oro City',
                'region_of_residence' => 'Region X – Northern Mindanao',
                'phone_number' => '09120000009',
                'email' => 'chs@g.msuiit.edu.ph',
                'password' => Hash::make('1234567890'),
                'role' => 'student',
            ],
            studentData: [
                'student_id' => '2023-1088',
                'year_level' => '2nd Year',
                'course' => 'Bachelor of Science in Nursing',
                'college_id' => 8,
                'msu_sase_score' => 88.2,
                'academic_year' => '2024-2025',
                'profile_picture' => null,
                'student_status' => 'new',
                'initial_interview_completed' => false,
            ],
            relations: [
                'personal' => [
                    'nickname' => 'Mari',
                    'home_address' => 'Cagayan de Oro City',
                    'stays_with' => 'relatives',
                    'working_student' => 'no but planning to work',
                    'talents_skills' => ['caregiving', 'communication', 'first aid'],
                    'leisure_activities' => ['reading medical journals', 'volunteering'],
                    'serious_medical_condition' => 'None',
                    'physical_disability' => 'None',
                    'sex_identity' => 'female/woman',
                    'romantic_attraction' => 'opposite sex',
                ],
                'family' => [
                    'father_name' => 'Ricardo Reyes',
                    'father_deceased' => false,
                    'father_occupation' => 'Driver',
                    'father_phone_number' => '09120000091',
                    'mother_name' => 'Lourdes Reyes',
                    'mother_deceased' => false,
                    'mother_occupation' => 'Nurse',
                    'mother_phone_number' => '09120000092',
                    'parents_marital_status' => 'married',
                    'family_monthly_income' => '15001-20000',
                    'guardian_name' => null,
                    'guardian_occupation' => null,
                    'guardian_phone_number' => null,
                    'guardian_relationship' => null,
                    'ordinal_position' => 'eldest',
                    'number_of_siblings' => 2,
                    'home_environment_description' => 'Supportive family environment',
                ],
                'academic' => [
                    'shs_gpa' => 91.0,
                    'is_scholar' => false,
                    'scholarship_type' => null,
                    'school_last_attended' => 'Cagayan de Oro National High School',
                    'school_address' => 'Cagayan de Oro City',
                    'shs_track' => 'academic',
                    'shs_strand' => 'STEM',
                    'awards_honors' => ['With Honors'],
                    'student_organizations' => ['Nursing Society'],
                    'co_curricular_activities' => ['Health Awareness Campaign'],
                    'career_option_1' => 'Registered Nurse',
                    'career_option_2' => 'Medical Professional',
                    'career_option_3' => null,
                    'course_choice_by' => 'own choice',
                    'course_choice_reason' => 'Passion for helping and caring for others',
                    'msu_choice_reasons' => ['quality education', 'affordable tuition fees'],
                    'future_career_plans' => 'Work as a nurse locally then pursue opportunities abroad',
                ],
                'learning_resources' => [
                    'internet_access' => 'full internet access',
                    'technology_gadgets' => ['laptop/notebook', 'mobile phone smartphone'],
                    'internet_connectivity' => ['home internet', 'mobile data'],
                    'distance_learning_readiness' => 'ready',
                    'learning_space_description' => 'Shared room with study desk',
                ],
                'psychosocial' => [
                    'personality_characteristics' => ['caring', 'patient', 'hardworking'],
                    'coping_mechanisms' => ['talking to friends', 'praying'],
                    'mental_health_perception' => 'Generally good',
                    'had_counseling_before' => false,
                    'sought_psychologist_help' => false,
                    'problem_sharing_targets' => ['mother', 'friends'],
                    'needs_immediate_counseling' => false,
                    'future_counseling_concerns' => 'Academic workload and career decisions',
                ],
                'needs_assessment' => [
                    'improvement_needs' => ['Time-management skills', 'Study habits'],
                    'financial_assistance_needs' => ['Grants/scholarships'],
                    'personal_social_needs' => ['Stress management'],
                    'stress_responses' => ['Tried to solve my problem', 'Talked to someone'],
                    'easy_discussion_target' => 'friends/relatives',
                    'counseling_perceptions' => [
                        'I know that help is available at the Guidance and Counseling Center of MSU-IIT.' => 'always',
                        'I am shy to ask assistance/seek counseling from my guidance counselor.' => 'sometimes',
                    ],
                ],
            ]
        );

        $this->seedStudent(
            userData: [
                'first_name' => 'Juan',
                'middle_name' => 'Dela Cruz',
                'last_name' => 'Santos',
                'birthdate' => '2003-06-11',
                'age' => 21,
                'sex' => 'male',
                'birthplace' => 'Iligan City',
                'religion' => 'Catholic',
                'civil_status' => 'single',
                'number_of_children' => 0,
                'citizenship' => 'Filipino',
                'address' => 'Iligan City',
                'region_of_residence' => 'Region X – Northern Mindanao',
                'phone_number' => '09120000001',
                'email' => 'cass@g.msuiit.edu.ph',
                'password' => Hash::make('1234567890'),
                'role' => 'student',
            ],
            studentData: [
                'student_id' => '2023-1001',
                'year_level' => '1st Year',
                'course' => 'Bachelor of Arts in English',
                'college_id' => 1,
                'msu_sase_score' => 82.7,
                'academic_year' => '2024-2025',
                'profile_picture' => null,
                'student_status' => 'new',
                'initial_interview_completed' => false,
            ],
            relations: [
                'personal' => [
                    'nickname' => 'John',
                    'home_address' => 'Palao, Iligan City',
                    'stays_with' => 'board/roommates',
                    'working_student' => 'yes part time',
                    'talents_skills' => ['writing', 'public speaking', 'research'],
                    'leisure_activities' => ['reading novels', 'debating'],
                    'serious_medical_condition' => 'None',
                    'physical_disability' => 'None',
                    'sex_identity' => 'male/man',
                    'romantic_attraction' => 'both men and women',
                ],
                'family' => [
                    'father_name' => 'Pedro Santos',
                    'father_deceased' => false,
                    'father_occupation' => 'Farmer',
                    'father_phone_number' => '09120000011',
                    'mother_name' => 'Lucia Santos',
                    'mother_deceased' => false,
                    'mother_occupation' => 'Housewife',
                    'mother_phone_number' => '09120000012',
                    'parents_marital_status' => 'married',
                    'family_monthly_income' => '8001-10000',
                    'guardian_name' => null,
                    'guardian_occupation' => null,
                    'guardian_phone_number' => null,
                    'guardian_relationship' => null,
                    'ordinal_position' => 'middle',
                    'number_of_siblings' => 3,
                    'home_environment_description' => 'Simple but loving family environment',
                ],
                'academic' => [
                    'shs_gpa' => 88.0,
                    'is_scholar' => false,
                    'scholarship_type' => null,
                    'school_last_attended' => 'Palao National High School',
                    'school_address' => 'Iligan City',
                    'shs_track' => 'academic',
                    'shs_strand' => 'HUMMS',
                    'awards_honors' => ['With Honors'],
                    'student_organizations' => ['Literary Club'],
                    'co_curricular_activities' => ['Debate Competition'],
                    'career_option_1' => 'Writer',
                    'career_option_2' => 'Teacher',
                    'career_option_3' => 'Journalist',
                    'course_choice_by' => 'own choice',
                    'course_choice_reason' => 'Love for literature and language',
                    'msu_choice_reasons' => ['quality education', 'affordable tuition fees'],
                    'future_career_plans' => 'Become a published author and educator',
                ],
                'learning_resources' => [
                    'internet_access' => 'limited internet access',
                    'technology_gadgets' => ['mobile phone smartphone'],
                    'internet_connectivity' => ['mobile data'],
                    'distance_learning_readiness' => 'a little ready',
                    'learning_space_description' => 'Shared boarding room',
                ],
                'psychosocial' => [
                    'personality_characteristics' => ['creative', 'expressive', 'sociable'],
                    'coping_mechanisms' => ['writing', 'talking to friends'],
                    'mental_health_perception' => 'Mostly good, occasional anxiety',
                    'had_counseling_before' => false,
                    'sought_psychologist_help' => false,
                    'problem_sharing_targets' => ['friends', 'siblings'],
                    'needs_immediate_counseling' => false,
                    'future_counseling_concerns' => 'Academic adjustment and social concerns',
                ],
                'needs_assessment' => [
                    'improvement_needs' => ['Study habits', 'Test-taking skills'],
                    'financial_assistance_needs' => ['Grants/scholarships', 'Part-time job assistance'],
                    'personal_social_needs' => ['Stress management', 'Motivation'],
                    'stress_responses' => ['Tried to solve my problem', 'Listened to music'],
                    'easy_discussion_target' => 'friends/relatives',
                    'counseling_perceptions' => [
                        'I know that help is available at the Guidance and Counseling Center of MSU-IIT.' => 'sometimes',
                        'I am shy to ask assistance/seek counseling from my guidance counselor.' => 'often',
                    ],
                ],
            ]
        );

        $this->seedStudent(
            userData: [
                'first_name' => 'Carlos',
                'middle_name' => 'Miguel',
                'last_name' => 'Gonzales',
                'birthdate' => '2002-09-15',
                'age' => 22,
                'sex' => 'male',
                'birthplace' => 'Iligan City',
                'religion' => 'Christian',
                'civil_status' => 'single',
                'number_of_children' => 0,
                'citizenship' => 'Filipino',
                'address' => 'Iligan City',
                'region_of_residence' => 'Region X – Northern Mindanao',
                'phone_number' => '09120000002',
                'email' => 'coe@g.msuiit.edu.ph',
                'password' => Hash::make('1234567890'),
                'role' => 'student',
            ],
            studentData: [
                'student_id' => '2023-1002',
                'year_level' => '3rd Year',
                'course' => 'Bachelor of Science in Civil Engineering',
                'college_id' => 2,
                'msu_sase_score' => 87.9,
                'academic_year' => '2024-2025',
                'profile_picture' => null,
                'student_status' => 'returnee',
                'initial_interview_completed' => true,
            ],
            relations: [
                'personal' => [
                    'nickname' => 'Caloy',
                    'home_address' => 'Tominobo, Iligan City',
                    'stays_with' => 'living on my own',
                    'working_student' => 'yes full time',
                    'talents_skills' => ['drafting', 'calculations', 'project management'],
                    'leisure_activities' => ['basketball', 'engineering projects'],
                    'serious_medical_condition' => 'None',
                    'physical_disability' => 'None',
                    'sex_identity' => 'male/man',
                    'romantic_attraction' => 'opposite sex',
                ],
                'family' => [
                    'father_name' => 'Eduardo Gonzales',
                    'father_deceased' => false,
                    'father_occupation' => 'Construction Worker',
                    'father_phone_number' => '09120000021',
                    'mother_name' => 'Carmen Gonzales',
                    'mother_deceased' => false,
                    'mother_occupation' => 'Vendor',
                    'mother_phone_number' => '09120000022',
                    'parents_marital_status' => 'married',
                    'family_monthly_income' => '10001-15000',
                    'guardian_name' => null,
                    'guardian_occupation' => null,
                    'guardian_phone_number' => null,
                    'guardian_relationship' => null,
                    'ordinal_position' => 'eldest',
                    'number_of_siblings' => 2,
                    'home_environment_description' => 'Hardworking family environment',
                ],
                'academic' => [
                    'shs_gpa' => 89.5,
                    'is_scholar' => false,
                    'scholarship_type' => null,
                    'school_last_attended' => 'Iligan City National High School',
                    'school_address' => 'Iligan City',
                    'shs_track' => 'academic',
                    'shs_strand' => 'STEM',
                    'awards_honors' => ['With Honors'],
                    'student_organizations' => ['Engineering Society'],
                    'co_curricular_activities' => ['Bridge Building Competition'],
                    'career_option_1' => 'Civil Engineer',
                    'career_option_2' => 'Project Manager',
                    'career_option_3' => null,
                    'course_choice_by' => 'own choice',
                    'course_choice_reason' => 'Interest in construction and infrastructure',
                    'msu_choice_reasons' => ['quality education', 'affordable tuition fees'],
                    'future_career_plans' => 'Work as a licensed civil engineer on infrastructure projects',
                ],
                'learning_resources' => [
                    'internet_access' => 'full internet access',
                    'technology_gadgets' => ['laptop/notebook', 'mobile phone smartphone'],
                    'internet_connectivity' => ['home internet'],
                    'distance_learning_readiness' => 'ready',
                    'learning_space_description' => 'Small apartment with study area',
                ],
                'psychosocial' => [
                    'personality_characteristics' => ['determined', 'practical', 'independent'],
                    'coping_mechanisms' => ['playing basketball', 'talking to friends'],
                    'mental_health_perception' => 'Good, manages stress through physical activity',
                    'had_counseling_before' => false,
                    'sought_psychologist_help' => false,
                    'problem_sharing_targets' => ['friends', 'siblings'],
                    'needs_immediate_counseling' => false,
                    'future_counseling_concerns' => 'Work-life balance and career planning',
                ],
                'needs_assessment' => [
                    'improvement_needs' => ['Time-management skills', 'Financial literacy'],
                    'financial_assistance_needs' => ['Grants/scholarships', 'Part-time job assistance'],
                    'personal_social_needs' => ['Stress management'],
                    'stress_responses' => ['Tried to solve my problem', 'Exercised'],
                    'easy_discussion_target' => 'friends/relatives',
                    'counseling_perceptions' => [
                        'I know that help is available at the Guidance and Counseling Center of MSU-IIT.' => 'sometimes',
                        'I am shy to ask assistance/seek counseling from my guidance counselor.' => 'sometimes',
                    ],
                ],
            ]
        );

        $this->seedStudent(
            userData: [
                'first_name' => 'Ana',
                'middle_name' => 'Marie',
                'last_name' => 'Lim',
                'birthdate' => '2003-05-20',
                'age' => 21,
                'sex' => 'female',
                'birthplace' => 'Iligan City',
                'religion' => 'Catholic',
                'civil_status' => 'single',
                'number_of_children' => 0,
                'citizenship' => 'Filipino',
                'address' => 'Iligan City',
                'region_of_residence' => 'Region X – Northern Mindanao',
                'phone_number' => '09120000003',
                'email' => 'coet@g.msuiit.edu.ph',
                'password' => Hash::make('1234567890'),
                'role' => 'student',
            ],
            studentData: [
                'student_id' => '2023-1003',
                'year_level' => '2nd Year',
                'course' => 'Bachelor of Science in Industrial Automation Engineering Technology',
                'college_id' => 3,
                'msu_sase_score' => 84.3,
                'academic_year' => '2024-2025',
                'profile_picture' => null,
                'student_status' => 'shiftee',
                'initial_interview_completed' => false,
            ],
            relations: [
                'personal' => [
                    'nickname' => 'Annie',
                    'home_address' => 'Tibanga, Iligan City',
                    'stays_with' => 'friends',
                    'working_student' => 'no and have no plan to work',
                    'talents_skills' => ['technical drawing', 'electronics', 'problem solving'],
                    'leisure_activities' => ['robotics', 'gaming'],
                    'serious_medical_condition' => 'None',
                    'physical_disability' => 'None',
                    'sex_identity' => 'female/woman',
                    'romantic_attraction' => 'prefer not to answer',
                ],
                'family' => [
                    'father_name' => 'Antonio Lim',
                    'father_deceased' => false,
                    'father_occupation' => 'Technician',
                    'father_phone_number' => '09120000031',
                    'mother_name' => 'Rosario Lim',
                    'mother_deceased' => false,
                    'mother_occupation' => 'Seamstress',
                    'mother_phone_number' => '09120000032',
                    'parents_marital_status' => 'married',
                    'family_monthly_income' => '10001-15000',
                    'guardian_name' => null,
                    'guardian_occupation' => null,
                    'guardian_phone_number' => null,
                    'guardian_relationship' => null,
                    'ordinal_position' => 'youngest',
                    'number_of_siblings' => 1,
                    'home_environment_description' => 'Quiet and supportive home environment',
                ],
                'academic' => [
                    'shs_gpa' => 87.0,
                    'is_scholar' => false,
                    'scholarship_type' => null,
                    'school_last_attended' => 'Tibanga National High School',
                    'school_address' => 'Iligan City',
                    'shs_track' => 'tech-voc',
                    'shs_strand' => null,
                    'awards_honors' => ['With Honors'],
                    'student_organizations' => ['Robotics Club'],
                    'co_curricular_activities' => ['Robotics Competition'],
                    'career_option_1' => 'Automation Engineer',
                    'career_option_2' => 'Electronics Technician',
                    'career_option_3' => null,
                    'course_choice_by' => 'own choice',
                    'course_choice_reason' => 'Interest in automation and electronics',
                    'msu_choice_reasons' => ['quality education', 'affordable tuition fees'],
                    'future_career_plans' => 'Work in industrial automation and eventually start a tech business',
                ],
                'learning_resources' => [
                    'internet_access' => 'full internet access',
                    'technology_gadgets' => ['laptop/notebook', 'mobile phone smartphone'],
                    'internet_connectivity' => ['home internet', 'mobile data'],
                    'distance_learning_readiness' => 'ready',
                    'learning_space_description' => 'Shared room with study corner',
                ],
                'psychosocial' => [
                    'personality_characteristics' => ['analytical', 'quiet', 'focused'],
                    'coping_mechanisms' => ['gaming', 'listening to music'],
                    'mental_health_perception' => 'Generally okay, sometimes stressed',
                    'had_counseling_before' => false,
                    'sought_psychologist_help' => false,
                    'problem_sharing_targets' => ['friends'],
                    'needs_immediate_counseling' => false,
                    'future_counseling_concerns' => 'Academic adjustment after shifting courses',
                ],
                'needs_assessment' => [
                    'improvement_needs' => ['Study habits', 'Time-management skills'],
                    'financial_assistance_needs' => ['Grants/scholarships'],
                    'personal_social_needs' => ['Stress management', 'Self-confidence'],
                    'stress_responses' => ['Tried to solve my problem', 'Listened to music'],
                    'easy_discussion_target' => 'friends/relatives',
                    'counseling_perceptions' => [
                        'I know that help is available at the Guidance and Counseling Center of MSU-IIT.' => 'sometimes',
                        'I am shy to ask assistance/seek counseling from my guidance counselor.' => 'often',
                    ],
                ],
            ]
        );

        $this->seedStudent(
            userData: [
                'first_name' => 'Sofia',
                'middle_name' => 'Isabel',
                'last_name' => 'Tan',
                'birthdate' => '2004-07-18',
                'age' => 20,
                'sex' => 'female',
                'birthplace' => 'Iligan City',
                'religion' => 'Christian',
                'civil_status' => 'single',
                'number_of_children' => 0,
                'citizenship' => 'Filipino',
                'address' => 'Iligan City',
                'region_of_residence' => 'Region X – Northern Mindanao',
                'phone_number' => '09120000004',
                'email' => 'ceba@g.msuiit.edu.ph',
                'password' => Hash::make('1234567890'),
                'role' => 'student',
            ],
            studentData: [
                'student_id' => '2023-1004',
                'year_level' => '1st Year',
                'course' => 'Bachelor of Science in Business Administration',
                'college_id' => 4,
                'msu_sase_score' => 86.1,
                'academic_year' => '2024-2025',
                'profile_picture' => null,
                'student_status' => 'transferee',
                'initial_interview_completed' => false,
            ],
            relations: [
                'personal' => [
                    'nickname' => 'Sophie',
                    'home_address' => 'Palao, Iligan City',
                    'stays_with' => 'parents/guardian',
                    'working_student' => 'no but planning to work',
                    'talents_skills' => ['leadership', 'negotiation', 'public speaking'],
                    'leisure_activities' => ['business case studies', 'networking events'],
                    'serious_medical_condition' => 'None',
                    'physical_disability' => 'None',
                    'sex_identity' => 'female/woman',
                    'romantic_attraction' => 'opposite sex',
                ],
                'family' => [
                    'father_name' => 'Henry Tan',
                    'father_deceased' => false,
                    'father_occupation' => 'Businessman',
                    'father_phone_number' => '09120000041',
                    'mother_name' => 'Grace Tan',
                    'mother_deceased' => false,
                    'mother_occupation' => 'Accountant',
                    'mother_phone_number' => '09120000042',
                    'parents_marital_status' => 'married',
                    'family_monthly_income' => '20001 above',
                    'guardian_name' => null,
                    'guardian_occupation' => null,
                    'guardian_phone_number' => null,
                    'guardian_relationship' => null,
                    'ordinal_position' => 'only child',
                    'number_of_siblings' => 0,
                    'home_environment_description' => 'Comfortable and supportive family environment',
                ],
                'academic' => [
                    'shs_gpa' => 92.0,
                    'is_scholar' => false,
                    'scholarship_type' => null,
                    'school_last_attended' => 'Palao National High School',
                    'school_address' => 'Iligan City',
                    'shs_track' => 'academic',
                    'shs_strand' => 'ABM',
                    'awards_honors' => ['With High Honors'],
                    'student_organizations' => ['Business Club', 'Student Council'],
                    'co_curricular_activities' => ['Business Plan Competition'],
                    'career_option_1' => 'Entrepreneur',
                    'career_option_2' => 'Business Manager',
                    'career_option_3' => 'Marketing Specialist',
                    'course_choice_by' => 'own choice',
                    'course_choice_reason' => 'Passion for business and entrepreneurship',
                    'msu_choice_reasons' => ['quality education', 'affordable tuition fees', 'prestigious institution'],
                    'future_career_plans' => 'Build my own business after gaining corporate experience',
                ],
                'learning_resources' => [
                    'internet_access' => 'full internet access',
                    'technology_gadgets' => ['laptop/notebook', 'mobile phone smartphone', 'tablet'],
                    'internet_connectivity' => ['home internet'],
                    'distance_learning_readiness' => 'fully ready',
                    'learning_space_description' => 'Dedicated study room at home',
                ],
                'psychosocial' => [
                    'personality_characteristics' => ['confident', 'ambitious', 'sociable'],
                    'coping_mechanisms' => ['talking to friends', 'journaling'],
                    'mental_health_perception' => 'Very good, handles pressure well',
                    'had_counseling_before' => false,
                    'sought_psychologist_help' => false,
                    'problem_sharing_targets' => ['mother', 'friends'],
                    'needs_immediate_counseling' => false,
                    'future_counseling_concerns' => 'Career direction and leadership development',
                ],
                'needs_assessment' => [
                    'improvement_needs' => ['Leadership skills', 'Time-management skills'],
                    'financial_assistance_needs' => ['Grants/scholarships'],
                    'personal_social_needs' => ['Motivation', 'Self-confidence'],
                    'stress_responses' => ['Tried to solve my problem', 'Talked to someone'],
                    'easy_discussion_target' => 'parents',
                    'counseling_perceptions' => [
                        'I know that help is available at the Guidance and Counseling Center of MSU-IIT.' => 'always',
                        'I am shy to ask assistance/seek counseling from my guidance counselor.' => 'rarely',
                    ],
                ],
            ]
        );

        $this->seedStudent(
            userData: [
                'first_name' => 'Miguel',
                'middle_name' => 'Antonio',
                'last_name' => 'Cruz',
                'birthdate' => '2003-08-09',
                'age' => 21,
                'sex' => 'male',
                'birthplace' => 'Iligan City',
                'religion' => 'Catholic',
                'civil_status' => 'single',
                'number_of_children' => 0,
                'citizenship' => 'Filipino',
                'address' => 'Iligan City',
                'region_of_residence' => 'Region X – Northern Mindanao',
                'phone_number' => '09120000005',
                'email' => 'ced@g.msuiit.edu.ph',
                'password' => Hash::make('1234567890'),
                'role' => 'student',
            ],
            studentData: [
                'student_id' => '2023-1005',
                'year_level' => '4th Year',
                'course' => 'Bachelor of Secondary Education',
                'college_id' => 5,
                'msu_sase_score' => 89.7,
                'academic_year' => '2024-2025',
                'profile_picture' => null,
                'student_status' => 'new',
                'initial_interview_completed' => true,
            ],
            relations: [
                'personal' => [
                    'nickname' => 'Mike',
                    'home_address' => 'Tominobo, Iligan City',
                    'stays_with' => 'relatives',
                    'working_student' => 'yes part time',
                    'talents_skills' => ['teaching', 'communication', 'lesson planning'],
                    'leisure_activities' => ['tutoring', 'reading educational materials'],
                    'serious_medical_condition' => 'None',
                    'physical_disability' => 'None',
                    'sex_identity' => 'male/man',
                    'romantic_attraction' => 'opposite sex',
                ],
                'family' => [
                    'father_name' => 'Jose Cruz',
                    'father_deceased' => false,
                    'father_occupation' => 'Security Guard',
                    'father_phone_number' => '09120000051',
                    'mother_name' => 'Marites Cruz',
                    'mother_deceased' => false,
                    'mother_occupation' => 'Teacher',
                    'mother_phone_number' => '09120000052',
                    'parents_marital_status' => 'married',
                    'family_monthly_income' => '15001-20000',
                    'guardian_name' => null,
                    'guardian_occupation' => null,
                    'guardian_phone_number' => null,
                    'guardian_relationship' => null,
                    'ordinal_position' => 'middle',
                    'number_of_siblings' => 2,
                    'home_environment_description' => 'Education-oriented family environment',
                ],
                'academic' => [
                    'shs_gpa' => 90.5,
                    'is_scholar' => true,
                    'scholarship_type' => 'Government Scholar',
                    'school_last_attended' => 'Tominobo National High School',
                    'school_address' => 'Iligan City',
                    'shs_track' => 'academic',
                    'shs_strand' => 'HUMMS',
                    'awards_honors' => ['With Honors', 'Best in English'],
                    'student_organizations' => ['Education Society', 'Debate Club'],
                    'co_curricular_activities' => ['Teaching Practicum', 'Debate Competition'],
                    'career_option_1' => 'High School Teacher',
                    'career_option_2' => 'School Administrator',
                    'career_option_3' => null,
                    'course_choice_by' => 'own choice',
                    'course_choice_reason' => 'Inspired by teachers and passion for education',
                    'msu_choice_reasons' => ['quality education', 'affordable tuition fees', 'prestigious institution'],
                    'future_career_plans' => 'Become a licensed professional teacher and eventually a school principal',
                ],
                'learning_resources' => [
                    'internet_access' => 'full internet access',
                    'technology_gadgets' => ['laptop/notebook', 'mobile phone smartphone'],
                    'internet_connectivity' => ['home internet', 'mobile data'],
                    'distance_learning_readiness' => 'fully ready',
                    'learning_space_description' => 'Quiet room at relatives house',
                ],
                'psychosocial' => [
                    'personality_characteristics' => ['patient', 'dedicated', 'empathetic'],
                    'coping_mechanisms' => ['tutoring others', 'praying'],
                    'mental_health_perception' => 'Good, finds fulfillment in helping others',
                    'had_counseling_before' => false,
                    'sought_psychologist_help' => false,
                    'problem_sharing_targets' => ['mother', 'friends'],
                    'needs_immediate_counseling' => false,
                    'future_counseling_concerns' => 'Work-life balance and career transition',
                ],
                'needs_assessment' => [
                    'improvement_needs' => ['Time-management skills', 'Test-taking skills'],
                    'financial_assistance_needs' => ['Grants/scholarships'],
                    'personal_social_needs' => ['Stress management', 'Motivation'],
                    'stress_responses' => ['Tried to solve my problem', 'Prayed'],
                    'easy_discussion_target' => 'parents',
                    'counseling_perceptions' => [
                        'I know that help is available at the Guidance and Counseling Center of MSU-IIT.' => 'always',
                        'I am shy to ask assistance/seek counseling from my guidance counselor.' => 'sometimes',
                    ],
                ],
            ]
        );

        $this->seedStudent(
            userData: [
                'first_name' => 'Elena',
                'middle_name' => 'Gabrielle',
                'last_name' => 'Rodriguez',
                'birthdate' => '2004-02-25',
                'age' => 21,
                'sex' => 'female',
                'birthplace' => 'Iligan City',
                'religion' => 'Christian',
                'civil_status' => 'single',
                'number_of_children' => 0,
                'citizenship' => 'Filipino',
                'address' => 'Iligan City',
                'region_of_residence' => 'Region X – Northern Mindanao',
                'phone_number' => '09120000006',
                'email' => 'csm@g.msuiit.edu.ph',
                'password' => Hash::make('1234567890'),
                'role' => 'student',
            ],
            studentData: [
                'student_id' => '2023-1006',
                'year_level' => '2nd Year',
                'course' => 'Bachelor of Science in Biology',
                'college_id' => 6,
                'msu_sase_score' => 91.2,
                'academic_year' => '2024-2025',
                'profile_picture' => null,
                'student_status' => 'new',
                'initial_interview_completed' => false,
            ],
            relations: [
                'personal' => [
                    'nickname' => 'Lena',
                    'home_address' => 'Tibanga, Iligan City',
                    'stays_with' => 'parents/guardian',
                    'working_student' => 'no and have no plan to work',
                    'talents_skills' => ['laboratory work', 'research', 'scientific writing'],
                    'leisure_activities' => ['nature walks', 'scientific experiments'],
                    'serious_medical_condition' => 'None',
                    'physical_disability' => 'None',
                    'sex_identity' => 'female/woman',
                    'romantic_attraction' => 'prefer not to answer',
                ],
                'family' => [
                    'father_name' => 'Ramon Rodriguez',
                    'father_deceased' => false,
                    'father_occupation' => 'Biologist',
                    'father_phone_number' => '09120000061',
                    'mother_name' => 'Cristina Rodriguez',
                    'mother_deceased' => false,
                    'mother_occupation' => 'Pharmacist',
                    'mother_phone_number' => '09120000062',
                    'parents_marital_status' => 'married',
                    'family_monthly_income' => '20001 above',
                    'guardian_name' => null,
                    'guardian_occupation' => null,
                    'guardian_phone_number' => null,
                    'guardian_relationship' => null,
                    'ordinal_position' => 'eldest',
                    'number_of_siblings' => 1,
                    'home_environment_description' => 'Science-oriented and nurturing family environment',
                ],
                'academic' => [
                    'shs_gpa' => 95.0,
                    'is_scholar' => true,
                    'scholarship_type' => 'Academic Scholar',
                    'school_last_attended' => 'Tibanga National High School',
                    'school_address' => 'Iligan City',
                    'shs_track' => 'academic',
                    'shs_strand' => 'STEM',
                    'awards_honors' => ['Valedictorian', 'Best in Science'],
                    'student_organizations' => ['Biology Society', 'Environmental Club'],
                    'co_curricular_activities' => ['Science Fair', 'Environmental Advocacy'],
                    'career_option_1' => 'Research Scientist',
                    'career_option_2' => 'Marine Biologist',
                    'career_option_3' => 'Environmental Consultant',
                    'course_choice_by' => 'own choice',
                    'course_choice_reason' => 'Fascination with living organisms and the natural world',
                    'msu_choice_reasons' => ['quality education', 'affordable tuition fees', 'prestigious institution'],
                    'future_career_plans' => 'Pursue graduate studies and contribute to scientific research',
                ],
                'learning_resources' => [
                    'internet_access' => 'full internet access',
                    'technology_gadgets' => ['laptop/notebook', 'mobile phone smartphone'],
                    'internet_connectivity' => ['home internet'],
                    'distance_learning_readiness' => 'fully ready',
                    'learning_space_description' => 'Quiet study room with good lighting',
                ],
                'psychosocial' => [
                    'personality_characteristics' => ['curious', 'methodical', 'introverted'],
                    'coping_mechanisms' => ['nature walks', 'reading'],
                    'mental_health_perception' => 'Good, finds peace in nature',
                    'had_counseling_before' => false,
                    'sought_psychologist_help' => false,
                    'problem_sharing_targets' => ['mother', 'close friends'],
                    'needs_immediate_counseling' => false,
                    'future_counseling_concerns' => 'Academic pressure and graduate school preparation',
                ],
                'needs_assessment' => [
                    'improvement_needs' => ['Time-management skills', 'Research skills'],
                    'financial_assistance_needs' => ['Grants/scholarships'],
                    'personal_social_needs' => ['Stress management'],
                    'stress_responses' => ['Tried to solve my problem', 'Listened to music'],
                    'easy_discussion_target' => 'parents',
                    'counseling_perceptions' => [
                        'I know that help is available at the Guidance and Counseling Center of MSU-IIT.' => 'always',
                        'I am shy to ask assistance/seek counseling from my guidance counselor.' => 'sometimes',
                    ],
                ],
            ]
        );

        $this->seedStudent(
            userData: [
                'first_name' => 'James',
                'middle_name' => 'Robert',
                'last_name' => 'Wilson',
                'birthdate' => '2003-11-30',
                'age' => 21,
                'sex' => 'male',
                'birthplace' => 'Iligan City',
                'religion' => 'Protestant',
                'civil_status' => 'single',
                'number_of_children' => 0,
                'citizenship' => 'Filipino',
                'address' => 'Iligan City',
                'region_of_residence' => 'Region X – Northern Mindanao',
                'phone_number' => '09120000007',
                'email' => 'student2@g.msuiit.edu.ph',
                'password' => Hash::make('1234567890'),
                'role' => 'student',
            ],
            studentData: [
                'student_id' => '2023-1007',
                'year_level' => '1st Year',
                'course' => 'Bachelor of Science in Information Technology',
                'college_id' => 7,
                'msu_sase_score' => 83.4,
                'academic_year' => '2024-2025',
                'profile_picture' => null,
                'student_status' => 'new',
                'initial_interview_completed' => false,
            ],
            relations: [
                'personal' => [
                    'nickname' => 'Jim',
                    'home_address' => 'Palao, Iligan City',
                    'stays_with' => 'board/roommates',
                    'working_student' => 'yes part time',
                    'talents_skills' => ['networking', 'system administration'],
                    'leisure_activities' => ['gaming', 'tech tutorials'],
                    'serious_medical_condition' => 'None',
                    'physical_disability' => 'None',
                    'sex_identity' => 'male/man',
                    'romantic_attraction' => 'opposite sex',
                ],
                'family' => [
                    'father_name' => 'Robert Wilson',
                    'father_deceased' => false,
                    'father_occupation' => 'IT Professional',
                    'father_phone_number' => '09120000071',
                    'mother_name' => 'Susan Wilson',
                    'mother_deceased' => false,
                    'mother_occupation' => 'Office Staff',
                    'mother_phone_number' => '09120000072',
                    'parents_marital_status' => 'married',
                    'family_monthly_income' => '15001-20000',
                    'guardian_name' => null,
                    'guardian_occupation' => null,
                    'guardian_phone_number' => null,
                    'guardian_relationship' => null,
                    'ordinal_position' => 'eldest',
                    'number_of_siblings' => 1,
                    'home_environment_description' => 'Tech-savvy and supportive family environment',
                ],
                'academic' => [
                    'shs_gpa' => 86.5,
                    'is_scholar' => false,
                    'scholarship_type' => null,
                    'school_last_attended' => 'Palao National High School',
                    'school_address' => 'Iligan City',
                    'shs_track' => 'academic',
                    'shs_strand' => 'STEM',
                    'awards_honors' => ['With Honors'],
                    'student_organizations' => ['IT Society'],
                    'co_curricular_activities' => ['Hackathon'],
                    'career_option_1' => 'Network Engineer',
                    'career_option_2' => 'System Administrator',
                    'career_option_3' => 'IT Consultant',
                    'course_choice_by' => 'own choice',
                    'course_choice_reason' => 'Interest in networking and system management',
                    'msu_choice_reasons' => ['quality education', 'affordable tuition fees'],
                    'future_career_plans' => 'Work as a network engineer in a tech company',
                ],
                'learning_resources' => [
                    'internet_access' => 'full internet access',
                    'technology_gadgets' => ['laptop/notebook', 'mobile phone smartphone'],
                    'internet_connectivity' => ['home internet', 'mobile data'],
                    'distance_learning_readiness' => 'fully ready',
                    'learning_space_description' => 'Boarding house room with desk',
                ],
                'psychosocial' => [
                    'personality_characteristics' => ['tech-savvy', 'independent', 'practical'],
                    'coping_mechanisms' => ['gaming', 'listening to music'],
                    'mental_health_perception' => 'Generally good',
                    'had_counseling_before' => false,
                    'sought_psychologist_help' => false,
                    'problem_sharing_targets' => ['friends', 'father'],
                    'needs_immediate_counseling' => false,
                    'future_counseling_concerns' => 'Academic adjustment and career planning',
                ],
                'needs_assessment' => [
                    'improvement_needs' => ['Study habits', 'Time-management skills'],
                    'financial_assistance_needs' => ['Part-time job assistance'],
                    'personal_social_needs' => ['Stress management'],
                    'stress_responses' => ['Tried to solve my problem', 'Listened to music'],
                    'easy_discussion_target' => 'friends/relatives',
                    'counseling_perceptions' => [
                        'I know that help is available at the Guidance and Counseling Center of MSU-IIT.' => 'sometimes',
                        'I am shy to ask assistance/seek counseling from my guidance counselor.' => 'often',
                    ],
                ],
            ]
        );

        $this->seedStudent(
            userData: [
                'first_name' => 'Andrea',
                'middle_name' => 'Nicole',
                'last_name' => 'Martinez',
                'birthdate' => '2004-04-12',
                'age' => 20,
                'sex' => 'female',
                'birthplace' => 'Iligan City',
                'religion' => 'Catholic',
                'civil_status' => 'single',
                'number_of_children' => 0,
                'citizenship' => 'Filipino',
                'address' => 'Iligan City',
                'region_of_residence' => 'Region X – Northern Mindanao',
                'phone_number' => '09120000008',
                'email' => 'student3@g.msuiit.edu.ph',
                'password' => Hash::make('1234567890'),
                'role' => 'student',
            ],
            studentData: [
                'student_id' => '2023-1008',
                'year_level' => '3rd Year',
                'course' => 'Bachelor of Science in Psychology',
                'college_id' => 1,
                'msu_sase_score' => 87.1,
                'academic_year' => '2024-2025',
                'profile_picture' => null,
                'student_status' => 'new',
                'initial_interview_completed' => true,
            ],
            relations: [
                'personal' => [
                    'nickname' => 'Andie',
                    'home_address' => 'Tibanga, Iligan City',
                    'stays_with' => 'parents/guardian',
                    'working_student' => 'no and have no plan to work',
                    'talents_skills' => ['counseling', 'active listening', 'empathy'],
                    'leisure_activities' => ['reading psychology books', 'meditation'],
                    'serious_medical_condition' => 'None',
                    'physical_disability' => 'None',
                    'sex_identity' => 'female/woman',
                    'romantic_attraction' => 'both men and women',
                ],
                'family' => [
                    'father_name' => 'Carlos Martinez',
                    'father_deceased' => false,
                    'father_occupation' => 'Social Worker',
                    'father_phone_number' => '09120000081',
                    'mother_name' => 'Patricia Martinez',
                    'mother_deceased' => false,
                    'mother_occupation' => 'Psychologist',
                    'mother_phone_number' => '09120000082',
                    'parents_marital_status' => 'married',
                    'family_monthly_income' => '20001 above',
                    'guardian_name' => null,
                    'guardian_occupation' => null,
                    'guardian_phone_number' => null,
                    'guardian_relationship' => null,
                    'ordinal_position' => 'youngest',
                    'number_of_siblings' => 1,
                    'home_environment_description' => 'Emotionally supportive and open family environment',
                ],
                'academic' => [
                    'shs_gpa' => 91.5,
                    'is_scholar' => false,
                    'scholarship_type' => null,
                    'school_last_attended' => 'Tibanga National High School',
                    'school_address' => 'Iligan City',
                    'shs_track' => 'academic',
                    'shs_strand' => 'HUMMS',
                    'awards_honors' => ['With Honors', 'Best in Social Science'],
                    'student_organizations' => ['Psychology Society', 'Peer Counseling Club'],
                    'co_curricular_activities' => ['Mental Health Awareness Campaign'],
                    'career_option_1' => 'Clinical Psychologist',
                    'career_option_2' => 'Guidance Counselor',
                    'career_option_3' => 'Researcher',
                    'course_choice_by' => 'own choice',
                    'course_choice_reason' => 'Passion for understanding human behavior and helping others',
                    'msu_choice_reasons' => ['quality education', 'affordable tuition fees', 'prestigious institution'],
                    'future_career_plans' => 'Become a licensed psychologist and open a mental health clinic',
                ],
                'learning_resources' => [
                    'internet_access' => 'full internet access',
                    'technology_gadgets' => ['laptop/notebook', 'mobile phone smartphone'],
                    'internet_connectivity' => ['home internet'],
                    'distance_learning_readiness' => 'fully ready',
                    'learning_space_description' => 'Comfortable study room at home',
                ],
                'psychosocial' => [
                    'personality_characteristics' => ['empathetic', 'reflective', 'open-minded'],
                    'coping_mechanisms' => ['meditation', 'journaling', 'talking to family'],
                    'mental_health_perception' => 'Very good, prioritizes mental wellness',
                    'had_counseling_before' => true,
                    'sought_psychologist_help' => false,
                    'problem_sharing_targets' => ['mother', 'close friends'],
                    'needs_immediate_counseling' => false,
                    'future_counseling_concerns' => 'Licensure exam preparation and career direction',
                ],
                'needs_assessment' => [
                    'improvement_needs' => ['Test-taking skills', 'Research skills'],
                    'financial_assistance_needs' => ['Grants/scholarships'],
                    'personal_social_needs' => ['Motivation', 'Self-confidence'],
                    'stress_responses' => ['Tried to solve my problem', 'Talked to someone'],
                    'easy_discussion_target' => 'parents',
                    'counseling_perceptions' => [
                        'I know that help is available at the Guidance and Counseling Center of MSU-IIT.' => 'always',
                        'I am shy to ask assistance/seek counseling from my guidance counselor.' => 'rarely',
                    ],
                ],
            ]
        );

        $this->seedStudent(
            userData: [
                'first_name' => 'Rose Andrea',
                'middle_name' => 'D',
                'last_name' => 'Kisol',
                'birthdate' => '2003-05-14',
                'age' => 22,
                'sex' => 'female',
                'birthplace' => 'Iligan City',
                'religion' => 'Roman Catholic',
                'civil_status' => 'single',
                'number_of_children' => 0,
                'citizenship' => 'Filipino',
                'address' => 'Tibanga, Iligan City',
                'region_of_residence' => 'Region X – Northern Mindanao',
                'phone_number' => '09171234567',
                'email' => 'roseandrea.kisol@g.msuiit.edu.ph',
                'password' => Hash::make('1234567890'),
                'role' => 'student',
            ],
            studentData: [
                'student_id' => '2022-3041',
                'year_level' => '3rd Year',
                'course' => 'Bachelor of Science in Computer Science',
                'college_id' => 7,
                'msu_sase_score' => 90.3,
                'academic_year' => '2024-2025',
                'student_status' => 'new',
                'initial_interview_completed' => true,
            ],
            relations: [
                'personal' => [
                    'nickname' => 'Rose',
                    'home_address' => 'Tibanga, Iligan City',
                    'stays_with' => 'parents/guardian',
                    'working_student' => 'no and have no plan to work',
                    'talents_skills' => json_encode(['programming', 'UI/UX design', 'problem solving']),
                    'leisure_activities' => json_encode(['reading', 'coding', 'drawing']),
                    'serious_medical_condition' => 'None',
                    'physical_disability' => 'None',
                    'sex_identity' => 'female/woman',
                    'romantic_attraction' => 'opposite sex',
                ],
                'family' => [
                    'father_name' => 'Roberto Kisol',
                    'father_deceased' => false,
                    'father_occupation' => 'Government Employee',
                    'father_phone_number' => '09181234567',
                    'mother_name' => 'Divina Kisol',
                    'mother_deceased' => false,
                    'mother_occupation' => 'Teacher',
                    'mother_phone_number' => '09191234567',
                    'parents_marital_status' => 'married',
                    'family_monthly_income' => '20001 above',
                    'guardian_name' => null,
                    'guardian_occupation' => null,
                    'guardian_phone_number' => null,
                    'guardian_relationship' => null,
                    'ordinal_position' => 'youngest',
                    'number_of_siblings' => 2,
                    'home_environment_description' => 'Warm and supportive family environment',
                ],
                'academic' => [
                    'shs_gpa' => 94.0,
                    'is_scholar' => true,
                    'scholarship_type' => 'Academic Scholar',
                    'school_last_attended' => 'Iligan City National High School',
                    'school_address' => 'Iligan City',
                    'shs_track' => 'academic',
                    'shs_strand' => 'STEM',
                    'awards_honors' => json_encode(['With Honors', 'Best in ICT']),
                    'student_organizations' => json_encode(['Computer Science Society', 'Women in Tech']),
                    'co_curricular_activities' => json_encode(['Hackathon', 'Programming Contest']),
                    'career_option_1' => 'Software Engineer',
                    'career_option_2' => 'UI/UX Designer',
                    'career_option_3' => 'Full Stack Developer',
                    'course_choice_by' => 'own choice',
                    'course_choice_reason' => 'Passion for technology and creating impactful software',
                    'msu_choice_reasons' => json_encode(['quality education', 'affordable tuition fees', 'close to home']),
                    'future_career_plans' => 'Work as a software engineer in a tech company and eventually build my own startup',
                ],
                'learning_resources' => [
                    'internet_access' => 'full internet access',
                    'technology_gadgets' => json_encode(['laptop/notebook', 'mobile phone smartphone', 'tablet']),
                    'internet_connectivity' => json_encode(['home internet', 'mobile data']),
                    'distance_learning_readiness' => 'fully ready',
                    'learning_space_description' => 'Dedicated study room with good lighting and fast internet',
                ],
                'psychosocial' => [
                    'personality_characteristics' => json_encode(['creative', 'determined', 'empathetic']),
                    'coping_mechanisms' => json_encode(['drawing', 'listening to music', 'talking to family']),
                    'mental_health_perception' => 'Generally positive, manages stress well',
                    'had_counseling_before' => false,
                    'sought_psychologist_help' => false,
                    'problem_sharing_targets' => json_encode(['mother', 'close friends']),
                    'needs_immediate_counseling' => false,
                    'future_counseling_concerns' => 'Career planning and academic workload management',
                ],
                'needs_assessment' => [
                    'improvement_needs' => json_encode(['Time-management skills', 'Study habits']),
                    'financial_assistance_needs' => json_encode(['Grants/scholarships']),
                    'personal_social_needs' => json_encode(['Stress management', 'Self-confidence']),
                    'stress_responses' => json_encode(['Listened to music', 'Attempted to end my life']),
                    'easy_discussion_target' => 'parents',
                    'counseling_perceptions' => json_encode([
                        'I know that help is available at the Guidance and Counseling Center of MSU-IIT.' => 'always',
                        'I am shy to ask assistance/seek counseling from my guidance counselor.' => 'rarely',
                    ]),
                ],
            ]
        );
    }

    private function seedStudent(array $userData, array $studentData, array $relations = []): void
    {
        $user = $this->upsertUser($userData);
        $student = $this->upsertStudent($user->id, $studentData);

        $modelMap = [
            'personal' => StudentPersonalData::class,
            'family' => StudentFamilyData::class,
            'academic' => StudentAcademicData::class,
            'learning_resources' => StudentLearningResources::class,
            'psychosocial' => StudentPsychosocialData::class,
            'needs_assessment' => StudentNeedsAssessment::class,
        ];

        foreach ($relations as $key => $data) {
            if (! isset($modelMap[$key])) {
                continue;
            }

            $modelClass = $modelMap[$key];
            $data = $this->normalizeCastedAttributes($modelClass, $data);

            $modelClass::updateOrCreate(
                ['student_id' => $student->id],
                $data
            );
        }
    }

    private function normalizeCastedAttributes(string $modelClass, array $attributes): array
    {
        $instance = new $modelClass();
        $casts = method_exists($instance, 'getCasts') ? $instance->getCasts() : [];

        foreach ($casts as $key => $castType) {
            if (! array_key_exists($key, $attributes)) {
                continue;
            }

            if ($castType !== 'array') {
                continue;
            }

            $value = $attributes[$key];
            if (is_string($value)) {
                $decoded = json_decode($value, true);
                if (json_last_error() === JSON_ERROR_NONE && is_array($decoded)) {
                    $attributes[$key] = $decoded;
                }
            }
        }

        return $attributes;
    }

    private function upsertUser(array $userData): User
    {
        $email = $userData['email'];
        unset($userData['email']);

        $userData['region_of_residence'] = $userData['region_of_residence'] ?? null;

        return User::updateOrCreate(
            ['email' => $email],
            $userData
        );
    }

    private function upsertStudent(int $userId, array $studentData): Student
    {
        $studentNumber = $studentData['student_id'];
        unset($studentData['student_id']);
        $studentData['user_id'] = $userId;

        $studentData['profile_picture'] = $studentData['profile_picture'] ?? null;

        if (! array_key_exists('initial_interview_completed', $studentData)) {
            $initialInterviewCompleted = null;
            $yearLevel = $studentData['year_level'] ?? null;
            if (in_array($yearLevel, ['1st Year', '2nd Year'], true)) {
                $initialInterviewCompleted = false;
            } elseif (in_array($yearLevel, ['3rd Year', '4th Year', '5th Year'], true)) {
                $initialInterviewCompleted = true;
            }
            $studentData['initial_interview_completed'] = $initialInterviewCompleted;
        }

        return Student::updateOrCreate(
            ['student_id' => $studentNumber],
            $studentData
        );
    }
}
